from __future__ import annotations

from typing import Dict, Iterable, List, Optional, Protocol, Tuple


class KnowledgeRepository(Protocol):
    def store(self, title: str, content: str, tags: Optional[List[str]] = None) -> str: ...

    def store_batch(
        self, items: Iterable[Tuple[str, str, Optional[List[str]]]]
    ) -> List[str]: ...

    def retrieve(self, content_id: str) -> Optional[Dict]: ...

    def delete(self, content_id: str) -> bool: ...

    def smart_search(self, query_text: str, max_results: int = 3) -> List[Dict]: ...

    def list_all(self) -> List[Dict]: ...

    def count(self) -> int: ...

    def get_stats(self) -> Dict: ...

    def clear_all(self) -> None: ...


__all__ = ["KnowledgeRepository"]
