from __future__ import annotations

from typing import Any, Dict, Optional

MODEL_REGISTRY: Dict[str, Dict[str, Any]] = {
    "AMBASSADOR": {
        "model": "openai/gpt-5.4-nano",
        "role": "Input Parser & Task Router",
        "tier": "AMBASSADOR",
        "priority": 0,
        "max_tokens": 300,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "CHAT_MODEL_STANDARD": {
        "model": "google/gemini-2.5-flash-lite",
        "role": "Chat Model",
        "tier": "CHAT",
        "priority": 0,
        "max_tokens": 3000,
        "temperature": 1.2,
        "top_p": 0.95,
    },
    "CHAT_MODEL_THINKING": {
        "model": "google/gemini-2.5-flash-lite:exacto",
        "role": "Chat Model (Thinking)",
        "tier": "CHAT",
        "priority": 0,
        "max_tokens": 4000,
        "temperature": 1.2,
        "top_p": 0.95,
    },
    "COMMANDER": {
        "model": "anthropic/claude-opus-4.6",
        "role": "Supreme Commander",
        "tier": "COMMAND",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.3,
        "top_p": 1.0,
    },
    "LEADER_LOW": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "LOW Task Leader",
        "tier": "LOW",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
    },
    "LEADER_MEDIUM": {
        "model": "minimax/minimax-m2.5",
        "role": "MEDIUM Task Leader",
        "tier": "MEDIUM",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
    },
    "LEADER_HIGH": {
        "model": "google/gemini-3.1-pro-preview",
        "role": "HIGH Task Leader",
        "tier": "HIGH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
    },
    "RESEARCHER": {
        "model": "x-ai/grok-4.1-fast",
        "role": "Research Specialist",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
    },
    "EXPERT": {
        "model": "moonshotai/kimi-k2.5",
        "role": "Architecture Expert",
        "tier": "HIGH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
    },
    "TOOL_CURATOR": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Tool & Dependency Manager",
        "tier": "LOW",
        "priority": 1,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "BROWSER": {
        "model": "perplexity/sonar",
        "role": "Web Browser Agent",
        "tier": "SUPPORT",
        "priority": 2,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "TEST_AGENT": {
        "model": "minimax/minimax-m2.7",
        "role": "Test Engineer",
        "tier": "MEDIUM",
        "priority": 2,
        "max_tokens": 4096,
        "temperature": 0.7,
        "top_p": 1.0,
    },
    "FAST_REVIEWER": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Code Reviewer",
        "tier": "REVIEW",
        "priority": 2,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
        "mode": {
            "standard": "Review bình thường, tập trung chất lượng thay đổi hiện tại.",
            "reflection": "Suy ngẫm lại lỗi sai, đổi hướng tư duy, rút kinh nghiệm rồi review lại.",
        },
    },
    "REVIEWER": {
        "model": "google/gemini-3-flash-preview",
        "role": "Technical Debt Specialist",
        "tier": "REVIEW",
        "priority": 2,
        "max_tokens": 8192,
        "temperature": 0.1,
        "top_p": 1.0,
        "mode": {
            "standard": "Review bình thường, tập trung technical debt và maintainability.",
            "reflection": "Suy ngẫm lại các lỗi sai còn sót, phản biện lại giả định, rồi review lại.",
        },
    },
    "FINAL_REVIEWER": {
        "model": "anthropic/claude-sonnet-4.6",
        "role": "Final Project Reviewer",
        "tier": "REVIEW",
        "priority": 2,
        "max_tokens": 8192,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "SECRETARY": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Terminal Executor",
        "tier": "SUPPORT",
        "priority": 2,
        "max_tokens": 2048,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "WORKER_A": {
        "model": "deepseek/deepseek-v3.2",
        "role": "Algorithm & Low-level Expert",
        "tier": "HARD",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "WORKER_B": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Fullstack & Clean Code Specialist",
        "tier": "MEDIUM",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "WORKER_C": {
        "model": "x-ai/grok-4.1-fast",
        "role": "For All Tasks Backup",
        "tier": "MEDIUM",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "WORKER_D": {
        "model": "z-ai/glm-4.7-flash",
        "role": "FullStack Backup ",
        "tier": "MEDIUM",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "WORKER_E": {
        "model": "qwen/qwen3.5-flash-02-23",
        "role": "FullStack Backup ",
        "tier": "MEDIUM",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
    },
    "FIX_WORKER": {
        "model": "minimax/minimax-m2.5",
        "role": "Bug Fixer",
        "tier": "LOW",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "ADVANCED_FIX_WORKER": {
        "model": "openai/gpt-5.4-mini",
        "role": "Deep Debugger",
        "tier": "HIGH",
        "priority": 4,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
    },
    "COMPACT_WORKER": {
        "model": "x-ai/grok-4.1-fast",
        "role": "Compact Worker",
        "tier": "Compact",
        "priority": 0,
        "max_tokens": 252000,
        "temperature": 0.6,
        "top_p": 0.95,
    },
}


TIER_MODEL_MAP = {
    "LOW": "xiaomi/mimo-v2-flash",
    "MEDIUM": "minimax/minimax-m2.5",
    "EXPERT": "moonshotai/kimi-k2.5",
    "HARD": "google/gemini-3.1-pro",
}

ASK_CHAT_STANDARD_MODEL = MODEL_REGISTRY["CHAT_MODEL_STANDARD"]["model"]
ASK_CHAT_THINKING_MODEL = MODEL_REGISTRY["CHAT_MODEL_THINKING"]["model"]


def get_worker_config(worker_id: str) -> Optional[Dict[str, Any]]:
    return MODEL_REGISTRY.get(worker_id.upper())


def get_model_for_tier(tier: str) -> str:
    return TIER_MODEL_MAP.get(tier.upper(), TIER_MODEL_MAP["MEDIUM"])
