"""Backward-compat shim — import from core.storage.ask_history directly."""
from core.storage.ask_history import (
    append_message,
    ask_data_dir,
    create_chat,
    delete_all_chats,
    delete_chat,
    delete_chats_bulk,
    ensure_chat,
    get_active_chat,
    join_chat,
    list_chat_records,
    list_chats,
    load_store,
    rename_chat,
    save_store,
    set_chat_mode,
)

__all__ = [
    "append_message",
    "ask_data_dir",
    "create_chat",
    "delete_all_chats",
    "delete_chat",
    "delete_chats_bulk",
    "ensure_chat",
    "get_active_chat",
    "join_chat",
    "list_chat_records",
    "list_chats",
    "load_store",
    "rename_chat",
    "save_store",
    "set_chat_mode",
]
