from __future__ import annotations

from typing import Any, Dict

REGISTRY: Dict[str, Dict[str, Any]] = {
    "FIX_WORKER_A": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Bug Fixer A",
        "reason": "Sửa lỗi mã nguồn và xử lý các vấn đề logic phát sinh.",
        "tier": "FIX",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "FIX_WORKER_B": {
        "model": "deepseek/deepseek-v3.2",
        "role": "Bug Fixer B",
        "reason": "Sửa lỗi mã nguồn và xử lý các vấn đề logic phát sinh.",
        "tier": "FIX",
        "priority": 4,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "FIX_WORKER_C": {
        "model": "deepseek/deepseek-v4-flash",
        "role": "Bug Fixer C",
        "reason": "Sửa lỗi mã nguồn và xử lý các vấn đề logic phát sinh.",
        "tier": "FIX",
        "priority": 4,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "ADVANCED_FIX_WORKER_A": {
        "model": "xiaomi/mimo-v2.5-pro",
        "role": "Production Fixer",
        "reason": "Khắc phục các sự cố kỹ thuật phức tạp và tối ưu hệ thống.",
        "tier": "FIX",
        "priority": 4,
        "max_tokens": 8192,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "enabled": True, "exclude": False},
    },
    "ADVANCED_FIX_WORKER_B": {
        "model": "deepseek/deepseek-v4-pro",
        "role": "Architecture Fixer",
        "reason": "Khắc phục các sự cố kỹ thuật phức tạp và tối ưu hệ thống.",
        "tier": "FIX",
        "priority": 4,
        "max_tokens": 16384,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "xhigh", "enabled": True, "exclude": False},
    },
    "ADVANCED_FIX_WORKER_C": {
        "model": "x-ai/grok-4.3",
        "role": "The Speed Sniper",
        "reason": "Khắc phục các sự cố kỹ thuật phức tạp và tối ưu hệ thống.",
        "tier": "FIX",
        "priority": 4,
        "max_tokens": 16384,
        "temperature": 0.1,
        "top_p": 1.0,
        "reasoning": {"effort": "xhigh", "enabled": True, "exclude": False},
    },
}
