from __future__ import annotations

from typing import Any, Dict

REGISTRY: Dict[str, Dict[str, Any]] = {
    "GENERAL_RESEARCHER": {
        "model": "qwen/qwen3.6-plus",
        "role": "Researcher",
        "reason": "Tổng hợp thông tin và cung cấp bối cảnh cho dự án.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "exclude": False},
    },
    "SYSTEMS_RESEARCHER": {
        "model": "x-ai/grok-4.3",
        "role": "Systems Researcher",
        "reason": "Nghien cuu he thong va ha tang: distributed systems, BFT, network protocols, safety/liveness trade-offs va vat ly thuc nghiem.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.4,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "exclude": False},
    },
    "METHODOLOGY_RESEARCHER": {
        "model": "deepseek/deepseek-v4-pro",
        "role": "Methodology Researcher",
        "reason": "Kien truc su quy trinh R&D: bio-informatics, chemistry simulation va thiet ke pipeline nghien cuu nhieu cong cu.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.35,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "exclude": False},
    },
    "AI_ALGORITHMIC_RESEARCHER": {
        "model": "deepseek/deepseek-v3.2",
        "role": "AI/Algorithmic Researcher",
        "reason": "Nghien cuu thuat toan AI: neural architecture search, optimization, deep learning theory va implement architecture tu zero.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.3,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "exclude": False},
    },
    "RESEARCH_SCOUT": {
        "model": "openai/gpt-4.1-nano",
        "role": "Research Scout",
        "reason": "Trinh sat nghien cuu: literature review, tom tat abstract va loc nhanh tinh kha thi truoc khi chuyen senior researcher.",
        "tier": "RESEARCH",
        "priority": 0,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "reasoning": {"effort": "low", "exclude": False},
    },
    "EMPIRICAL_SPECIALIST": {
        "model": "google/gemma-4-31b-it",
        "role": "Empirical Specialist",
        "reason": "Chuyen gia thuc nghiem: viet script mo phong, data analysis va kiem chung gia thuyet bang Python/Julia/R.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.25,
        "top_p": 1.0,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "TECHNICAL_RESEARCHER": {
        "model": "deepseek/deepseek-v4-flash",
        "role": "Tech Researcher",
        "reason": "Nghiên cứu tài liệu kỹ thuật và các thư viện chuyên sâu.",
        "tier": "RESEARCH",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
        "reasoning": {"effort": "high", "exclude": False},
    },
    "EXPERT": {
        "model": "google/gemini-3.1-pro-preview",
        "role": "Expert",
        "reason": "Handles expert-level planning, deep validation, and high-complexity technical reasoning.",
        "tier": "SPECIALIST",
        "priority": 1,
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 1.0,
        "reasoning": {"effort": "medium", "exclude": False},
    },
}
