from __future__ import annotations

from typing import Any, Dict

REGISTRY: Dict[str, Dict[str, Any]] = {
    "SECRETARY": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Secretary",
        "reason": "Thực thi lệnh terminal.",
        "tier": "SUPPORT",
        "priority": 2,
        "max_tokens": 2048,
        "temperature": 0.1,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "TOOL_CURATOR": {
        "model": "deepseek/deepseek-v4-flash",
        "role": "Tool Manager",
        "reason": "Quản lý thư viện, dependency và đề xuất công cụ phù hợp.",
        "tier": "SUPPORT",
        "priority": 1,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "BROWSER": {
        "model": "perplexity/sonar",
        "role": "Browser",
        "reason": "Tìm kiếm thông tin trực tuyến và xác minh tài liệu từ internet.",
        "tier": "SUPPORT",
        "priority": 2,
        "max_tokens": 4096,
        "temperature": 0.1,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "EXPLAINER": {
        "model": "nvidia/nemotron-3-super-120b-a12b",
        "role": "AI Explainer",
        "reason": "Giải thích các khái niệm kỹ thuật.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
}
