from __future__ import annotations

from typing import Any, Dict

REGISTRY: Dict[str, Dict[str, Any]] = {
    "WORKER_A": {
        "model": "deepseek/deepseek-v3.2",
        "role": "Backend Dev",
        "reason": "Phát triển Backend, xử lý thuật toán và hệ thống phân tán.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "WORKER_B": {
        "model": "xiaomi/mimo-v2-flash",
        "role": "Fullstack Dev",
        "reason": "Phát triển Fullstack, xây dựng API và logic nghiệp vụ.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "WORKER_C": {
        "model": "x-ai/grok-4.1-fast",
        "role": "UI Dev",
        "reason": "Phát triển UI/Frontend và tương tác người dùng.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "WORKER_D": {
        "model": "deepseek/deepseek-v4-flash",
        "role": "System Dev",
        "reason": "Chuyên xử lý các lỗi logic hệ thống tầng sâu.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "WORKER_E": {
        "model": "google/gemma-4-31b-it",
        "role": "Polymath Dev",
        "reason": "Hỗ trợ đa năng cho các tác vụ lập trình cơ bản.",
        "tier": "WORKER",
        "priority": 3,
        "max_tokens": 4096,
        "temperature": 0.2,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
    "DESIGNER": {
        "model": "qwen/qwen3.6-plus",
        "role": "Designer",
        "reason": "Thiet ke UX/UI, luong trai nghiem, visual system, layout, component states va su nhat quan san pham.",
        "tier": "DESIGN",
        "priority": 2,
        "max_tokens": 8192,
        "temperature": 0.4,
        "top_p": 1.0,
        "cache_enabled": True,
        "cache_ttl_seconds": 300,
        "reasoning": {"effort": "medium", "exclude": False},
    },
}
